config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get '/about' => 'statics#about'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_error'
  get '/422' => 'errors#unprocessable_entity'

  resources :posts do
    resources :comments, only: [:create]
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def name
    email
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  #attr_accessible :body, :title, :published, :author, :author_id

  has_many :comments

  belongs_to :author, class_name: "AdminUser"

  validates_presence_of :body, :title

  scope :published, -> { where(published: true) }

  def content
    MarkdownService.new.render(body)
  end

  def author_name
    if author
      author.name
    else
      "Admin"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create!(comment_params)
		respond_to do |format|
	      format.html { redirect_to @post }
	      format.js
	    end
	end


	private

	def comment_params
	    params.require(:comment).permit(:body)
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ActionController::Base
  layout 'application'

  def not_found
  end

  def internal_error
  end

  def unprocessable_entity
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  # GET /posts.atom
  def index
    @posts = Post.published

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.published.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def about
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
= div_for comment do
  %p
    %strong
      Posted #{time_ago_in_words(comment.created_at)} ago
    %br/
    = comment.body

app/views/comments/create.js.haml
$('#comments').append('#{escape_javascript(render partial: @comment)}');
$('#comment_body').val('')

app/views/home/index.html.haml
#home_section.wrapper
  .box-center.animated.fadeIn
    %h1.animated.bounceIn.delay-1 Siniša Mikulić
    %hr.animated.fadeInUp.delay-2
    %p.animated.fadeInUp.delay-3 Frontend developer
    .container.mt20
      .grid-6.grid-12-sm.mt20
        =link_to "Blog", "/posts", class: "btn btn-white btn-transparent animated flipInX delay-4"
      .grid-6.grid-12-sm.mt20
        =link_to "About", "#about_section", class: "btn btn-white btn-transparent animated flipInX delay-4 scroll"

.container
  #about_section
    .container
      .grid-6.grid-12-sm
        %h2.uppercase // About me
        %p Hello, my name is Siniša, currently living and working in Berlin as a frontend developer - HTML/Haml, CSS/SCSS, JS/JQuery/CoffeeScript, but with a lot of passion for Ruby on Rails and on a path towards full-stack skillset. Also pixel perfect junkie and absolutely love responsive design and clean code.
        =link_to "Download CV", "#", class: "btn btn-sm btn-orange mt20"
      .grid-6.grid-12-sm
        %h2.uppercase // Skills
        %ul.skills
          %li
            .progress.p100 HTML5/Haml
          %li
            .progress.p100 CSS3/Less/Sass
          %li
            .progress.p80 JavaScript/jQuery
          %li
            .progress.p70 Ruby on Rails
    .container
      .grid-6.grid-12-sm
        %h2.uppercase // Experience
        %ul.experience.timeline.cf
          %li
            .grid-2.grid-3-md
              .date 2014
            .grid-10.grid-9-md.job.mb10
              %h4.title
                =link_to "Outfittery", "http://www.outfittery.de/"
              %p.desc Implementing new JS features and modular structure using SCRUM. Ensuring code quality, reusability, CI deployment and compatibility across browsers/devices.
          %li
            .grid-2.grid-3-md
              .date 2014
            .grid-10.grid-9-md.job.mb10
              %h4.title
                =link_to "Bib + Tuck", "https://www.bibandtuck.com/"
              %p.desc Agile development (Ruby on Rails), new responsive design, code optimization, new features in HAML/SCSS/JavaScript technologies.
          %li
            .grid-2.grid-3-md
              .date 2013
            .grid-10.grid-9-md.job.mb10
              %h4.title
                =link_to "Styria", "http://www.styria.com/en/styria/"
              %p.desc 
                Developing and optimizing graphic templates into HTML/CSS/JavaScript, establishing a high quality and consistent UX and UI baseline, projects (e.g., 
                = link_to "barometar.hr", "http://barometar.vecernji.hr/"
                )
          %li
            .grid-2.grid-3-md
              .date 2012
            .grid-10.grid-9-md.job.mb10
              %h4.title
                =link_to "cleanpay.me", "http://cleanpay.me/"
              %p.desc Developing UX concepts and user interface (UI), wireframing, layout programming and styling HTML structure, cross-browser and cross-device testing, use case analyses and SEO optimization.
   
      .grid-6.grid-12-sm
        %h2.uppercase // Education
        %ul.experience.cf
          %li
            .grid-12.job.mb10
              %h4.title
                = link_to "University of Zagreb, Faculty of Organization and Informatics", "http://www.foi.unizg.hr/"
              %p.desc Information and Business Systems, BSc
          %li
            .grid-12.job.mb10
              %h4.title
                =link_to "Technical School Ruđer Bošković", "http://www.tsrb.hr/new/"
              %p.desc Technician for Computing Science, High School Graduate

        %h2.uppercase // Contact
        %ul.contact
          %li
            %i.fa.fa-2x.fa-envelope
            sinisa.mikulic@gmail.com
          %li
            %i.fa.fa-2x.fa-skype
            frut3k1

app/views/layouts/_footer.html.haml
.footer

app/views/layouts/_header.html.haml
%h1
  = link_to 'Sinisa Blog', root_path
  
= link_to 'About me', '/about'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Siniša Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = auto_discovery_link_tag(:atom, posts_path(:atom))
    = favicon_link_tag 'favicon.ico'
  %body
    //= render partial: 'layouts/header'
    = yield
    = render partial: 'layouts/footer'

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/posts/_post.html.haml
%h2= link_to_unless_current post.title, post
%h3
  Posted by: #{post.author_name}
= post.content.html_safe

app/views/posts/index.html.haml
%h1 Listing posts

= render partial: @posts

app/views/posts/show.html.haml
%p#notice= notice
= render partial: @post
= link_to 'Back', posts_path
%h2 Comments
#comments
  = render partial: @post.comments
= form_for [@post, Comment.new], remote: true do |f|
  %p
    = f.label :body, "New comment"
    %br/
    = f.text_area :body
  %p= f.submit "Add comment"

app/views/statics/about.html.haml
gg